Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SearchingSortingPagination.Models
{
    public class Trainer
    {
        public int TrainerId { get; set; }

        [Required(), MaxLength(60), MinLength(1)]
        [RegularExpression(@"^[^0-9]+$", ErrorMessage = "Characters are not allowed.")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(), MaxLength(60), MinLength(1)]
        [RegularExpression(@"^[^0-9]+$", ErrorMessage = "Characters are not allowed.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Range(0, Double.PositiveInfinity)]
        public decimal Salary { get; set; }

        public DateTime? HireDate { get; set; }

        [Display(Name = "Is Available")]
        public bool isAvailable { get; set; }

        //navigation properties
        [Display(Name = "Categories")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}

Controllers/TrainerController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SearchingSortingPagination.Dal;
using SearchingSortingPagination.Models;
using PagedList.Mvc;
using PagedList;
using SearchingSortingPagination.Utilities;
using System.Collections.Generic;

namespace SearchingSortingPagination.Controllers
{
    public class TrainerController : Controller
    {
        private MyDatabase db = new MyDatabase();

        // GET: Trainer
        public ActionResult Index(string searchFirstName, string searchLastName, int? searchMinSalary, int? searchMaxSalary, 
            DateTime? searchMinDate, DateTime? searchMaxDate, bool? searchIsAvailable, string sortOrder, int? pSize, int? page)
        {

            var trainers = db.Trainers.ToList();

            #region DucheBags
            ViewBag.FNSP = String.IsNullOrEmpty(sortOrder) ? "FirstNameDesc" : ""; //FNSP FirstNameSortP

            ViewBag.LNSP = sortOrder == "LastNameAsc" ? "LastNameDesc" : "LastNameAsc"; //LNSP LastNameSortP
            
            ViewBag.SSSP = sortOrder == "SalaryAsc" ? "SalaryDesc" : "SalaryAsc"; //SSSP SalarySSortP

            ViewBag.HDSP = sortOrder == "HireDateAsc" ? "HireDateDesc" : "HireDateAsc";

            ViewBag.Current_Sorting = sortOrder;


            ViewBag.Filter_FName = searchFirstName;
            ViewBag.Filter_LName = searchLastName;
            ViewBag.Filter_MinSalary = searchMinSalary;
            ViewBag.Filter_MaxSalary = searchMaxSalary;
            ViewBag.Filter_MinDate = searchMinDate;
            ViewBag.Filter_MaxDate = searchMaxDate;
            ViewBag.Filter_Available = searchIsAvailable;
            #endregion

            #region Filtering

            if (!String.IsNullOrWhiteSpace(searchFirstName))
                trainers = trainers.Where(x => x.FirstName.ToUpper().Contains(searchFirstName.ToUpper())).ToList();

            if (!String.IsNullOrWhiteSpace(searchLastName))
                trainers = trainers.Where(x => x.LastName.ToUpper().Contains(searchLastName.ToUpper())).ToList();

            if (searchMinSalary!= null)
                    trainers = trainers.Where(x => x.Salary >= searchMinSalary).ToList();

            if (searchMaxSalary != null)
                        trainers = trainers.Where(x => x.Salary <= searchMaxSalary).ToList();

            if (searchMinDate != null)
                trainers = trainers.Where(x => Validator.Compare(x.HireDate, searchMinDate) >= 0).ToList();

            if (searchMaxDate != null)
                trainers = trainers.Where(x => Validator.Compare(x.HireDate, searchMaxDate) <= 0).ToList();

            if (searchIsAvailable != null)
                trainers = trainers.Where(x => x.isAvailable == (bool)searchIsAvailable).ToList();


            #endregion

            #region Sorting
            switch (sortOrder)
            {
                case "FirstNameDesc": 
                    trainers = trainers.OrderByDescending(x => x.FirstName).ToList(); 
                    break;
                case "LastNameAsc": 
                    trainers = trainers.OrderBy(x => x.LastName).ToList(); 
                    break;
                case "LastNameDesc": 
                    trainers = trainers.OrderByDescending(x => x.LastName).ToList(); 
                    break;
                case "SalaryAsc": 
                    trainers = trainers.OrderBy(x => x.Salary).ToList(); 
                    break;
                case "SalaryDesc": 
                    trainers = trainers.OrderByDescending(x => x.Salary).ToList(); 
                    break;
                case "HireDateAsc":
                    trainers = trainers.OrderBy(x => x.HireDate).ToList();
                    break;
                case "HireDateDesc":
                    trainers = trainers.OrderByDescending(x => x.HireDate).ToList();
                    break;
                default: 
                    trainers = trainers.OrderBy(x => x.FirstName).ToList(); 
                    break;
            }
            #endregion

            #region pagination
            int pageSize = pSize ?? 5;
            int pageNumber = page ?? 1;
            #endregion

            return View(trainers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        public ActionResult CategoryDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            ViewBag.SelectedCategoriesIds = db.Categories.ToList().Select(x => new SelectListItem()
            {
                Value = x.CategoryId.ToString(),
                Text = x.Kind
            });
            

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TrainerId,FirstName,LastName,Salary,HireDate,isAvailable")] Trainer trainer, IEnumerable<int> SelectedCategoriesIds) 
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Attach(trainer);
                db.Entry(trainer).Collection("Categories").Load();
                trainer.Categories.Clear();
                db.SaveChanges();

                if (SelectedCategoriesIds != null)
                {
                    foreach (var id in SelectedCategoriesIds)
                    {
                        Category category = db.Categories.Find(id);
                        if (category != null)
                        {
                            trainer.Categories.Add(category);
                        }
                    }
                }

                db.Entry(trainer).State = EntityState.Added;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.SelectedCategoriesIds = db.Categories.ToList().Select(x => new SelectListItem()
            {
                Value = x.CategoryId.ToString(),
                Text = x.Kind
            });

            return View(trainer);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }

            var categoryIds = trainer.Categories.Select(x => x.CategoryId);
            ViewBag.SelectedCategoriesIds = db.Categories.ToList().Select(x => new SelectListItem()
            {
                Value = x.CategoryId.ToString(),
                Text = x.Kind,
                Selected = categoryIds.Any(y=>y==x.CategoryId)
            });

            return View(trainer);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TrainerId,FirstName,LastName,Salary,HireDate,isAvailable")] Trainer trainer, IEnumerable<int> SelectedCategoriesIds)
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Attach(trainer);
                db.Entry(trainer).Collection("Categories").Load();
                trainer.Categories.Clear();
                db.SaveChanges();

                if (SelectedCategoriesIds != null)
                {
                    foreach (var id in SelectedCategoriesIds)
                    {
                        Category category = db.Categories.Find(id);
                        if (category != null)
                        {
                            trainer.Categories.Add(category);
                        }
                    }
                }

                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.SelectedCategoriesIds = db.Categories.ToList().Select(x => new SelectListItem()
            {
                Value = x.CategoryId.ToString(),
                Text = x.Kind
            });

            return View(trainer);
        }

        // GET: Trainer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainer trainer = db.Trainers.Find(id);
            trainer.Categories.Clear();
            db.Entry(trainer).State = EntityState.Modified;
            db.SaveChanges();

            db.Entry(trainer).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Trainer/CategoryDetails.cshtml
@model SearchingSortingPagination.Models.Category

@{
    ViewBag.Title = "CategoryDetails";
}

<h2>Category Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kind):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kind)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Trainer/Create.cshtml
@model SearchingSortingPagination.Models.Trainer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*FIRST NAME*@
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*LAST NAME*@
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*SALARY*@
        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        @*DATE HIRED*@
        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>


        @*IS AVAILABLE*@
        <div class="form-group">
            @Html.LabelFor(model => model.isAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isAvailable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isAvailable, "", new { @class = "text-danger" })
            </div>
        </div>

        @* CATEGORIES *@
        <div class="form-group">
            @Html.Label("SelectedCategoriesIds", "Categories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedCategoriesIds", null, new { @class = "form-control", size = "7" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                dateFormat: "yy/mm/dd",
                changemonth: true,
                changeyear: true
            });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Trainer/Delete.cshtml
@model SearchingSortingPagination.Models.Trainer
@using SearchingSortingPagination.Utilities;

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.HireDate):
        </dt>

        <dd>
            @if (Model.HireDate != null)
            {
                <text>@Converter.RemoveNull(Model.HireDate).ToString("d")</text>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isAvailable):
        </dt>

        <dd>
            @if (Model.isAvailable)
            {
                <div class="col-lg-1 glyphicon glyphicon-ok"></div>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories):
        </dt>


        <dd>
            <ul style="list-style-type:none">
                @foreach (var item in Model.Categories)
                {
                    <li>
                        <a href="#"> @item.Kind</a>
                    </li>
                }
            </ul>
        </dd>

    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Trainer/Details.cshtml
@model SearchingSortingPagination.Models.Trainer
@using SearchingSortingPagination.Utilities;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HireDate):
        </dt>

        <dd>
            @if (Model.HireDate != null)
            {
                <text>@Converter.RemoveNull(Model.HireDate).ToString("d")</text>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isAvailable):
        </dt>

        <dd>
            @if (Model.isAvailable)
            {
                <div class="col-lg-1 glyphicon glyphicon-ok"></div>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories):
        </dt>

        
        <dd>
            <ul style="list-style-type:none">
                @foreach (var item in Model.Categories)
                {
                <li>
                    @Html.ActionLink(item.Kind, "CategoryDetails", new { id = item.CategoryId })
                </li>
                }
            </ul>
        </dd>
        

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Trainer/Edit.cshtml
@model SearchingSortingPagination.Models.Trainer
@using SearchingSortingPagination.Utilities;

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TrainerId)

        @*FIRST NAME*@
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*LAST NAME*@
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*SALARY*@
        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        @*HIRE DATE*@
        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>


        @*IS AVAILABLE*@
        <div class="form-group">
            @Html.LabelFor(model => model.isAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isAvailable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isAvailable, "", new { @class = "text-danger" })
            </div>
        </div>


        @* CATEGORIES *@
        <div class="form-group">
            @Html.Label("SelectedCategoriesIds", "Categories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedCategoriesIds", null, new { @class = "form-control", size = "7" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                dateFormat: "yy/mm/dd",
                changemonth: true,
                changeyear: true
            });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Trainer/Index.cshtml
@model PagedList.IPagedList<SearchingSortingPagination.Models.Trainer>
@using PagedList;
@using PagedList.Mvc;
@using SearchingSortingPagination.Utilities;

@{
    ViewBag.Title = "Index";
}

<h2>Trainers</h2>



@if (!(Model.PageCount < Model.PageNumber))
{

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>


    using (Html.BeginForm("index", "Trainer", FormMethod.Get))
    {
        <div id="overall">
            <div id="div0">
                @Html.TextBox("searchFirstName", null, new { @class = "form-control", placeholder = "Search First Name", type = "search" })
                @Html.TextBox("searchLastName", null, new { @class = "form-control", placeholder = "Search Last Name", type = "search" })
            </div>
            <div id="div1">
                @Html.TextBox("searchMinDate", null, new { @class = "form-control datepicker", placeholder = "Search Minimum Date Hired", type = "search" })
                @Html.TextBox("searchMaxDate", null, new { @class = "form-control datepicker", placeholder = "Search Maximum Date Hired", type = "search" })
            </div>
            <div id="div2">
                @Html.TextBox("searchMinSalary", null, new { @class = "form-control", placeholder = "Search Minimum Salary", type = "search" })
                @Html.TextBox("searchMaxSalary", null, new { @class = "form-control", placeholder = "Search Maximum Salary", type = "search" })
            </div>
            <div id="div3">
                @Html.TextBox("searchIsAvailable", null, new { @class = "form-control", placeholder = "Search for availability", type = "search" })
            </div>
        </div>

        <div id="divsub">
            <input type="submit" value="Search Trainer" class="btn btn-primary" />
            <input id="ResetButton" type="button" value="Clear Form" class="btn btn-success" />
        </div>
    }


    <table class="table table-hover">
        <tr>
            <th>
                @Html.ActionLink("First Name", "Index", "Trainer", new { sortOrder = "FirstNameDesc" }, null)
            </th>
            <th>
                @Html.ActionLink("Last Name", "Index", "Trainer", new { sortOrder = ViewBag.LNSP }, null)
            </th>
            <th>
                @Html.ActionLink("Salary", "Index", "Trainer", new { sortOrder = ViewBag.SSSP }, null)
            </th>
            <th>
                @Html.ActionLink("Hire Date", "Index", "Trainer", new { sortOrder = ViewBag.HDSP }, null)
            </th>
            <th class="text-primary">
                @Html.DisplayNameFor(model => model.First().isAvailable)
            </th>
            <th class="text-primary">
                Categories
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @if (item.HireDate != null)
                    {
                        <text>@Converter.RemoveNull(item.HireDate).ToString("d")</text>
                    }
                    else
                    {
                        <div class="col-lg-1">N/A</div>
                    }
                </td>
                <td>
                    @if (item.isAvailable)
                    {
                        <div class="col-lg-1 glyphicon glyphicon-ok"></div>
                    }
                </td>
                <td>
                    <ul>
                        @foreach (var category in item.Categories)
                        {
                            <li>
                                @Html.ActionLink(category.Kind, "CategoryDetails", new { id = category.CategoryId })
                            </li>
                        }
                    </ul>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.TrainerId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.TrainerId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.TrainerId })
                </td>
            </tr>
        }

    </table>

    <i>Page</i> @Model.PageNumber <i>of</i> @Model.PageCount
    <div class="pager">
        @Html.PagedListPager(Model, x => Url.Action("Index", "Trainer", new
   {
       page = x,
       searchFirstName = ViewBag.Filter_FName,
       searchLastName = ViewBag.Filter_LName,
       searchMinSalary = ViewBag.Filter_MinSalary,
       searchMaxSalary = ViewBag.Filter_MaxSalary,
       searchMinDate = ViewBag.Filter_MinDate,
       searchMaxDate = ViewBag.Filter_MaxDate,
       searchIsAvailable = ViewBag.Filter_Available,
       sortOrder = ViewBag.Current_Sorting
   }))
    </div>


}
else
{
    <h1>No data in Database</h1>
}







@section MyCustomCSS {
    <style>
        body {
            background-color: blanchedalmond;
        }

        #div0, #div1, #div2, #div3 {
            display: inline-block;
        }

        #divsub {
            padding: 5px 0px 20px 10px;
        }

        #overall {
            border-width: 3px;
            border-style: outset;
        }
    </style>
}

@section MyCustomJavascript {

    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

        

    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd-mm-yy",
                changemonth: true,
                changeyear: true
            });
        });

        $("#ResetButton").click(function (e) {
            e.preventDefault();
            $("#searchFirstName").val("");
            $("#searchLastName").val("");
            $("#searchMinSalary").val("");
            $("#searchMaxSalary").val("");
            $("#searchMaxDate").val("");
            $("#searchMinDate").val("");
            $("#searchIsAvailable").val("");

        });
    </script>
}